SELECT id_original, 
  latitude, 
  longitude, 
  emdcardnumber, 
  time_utc, 
  time_local, 
  response_time_sec, 
  day_of_week, 
  weekend_or_not, 
  geometry, 
  incident_id, 
  dist_to_seg, 
  xdsegid, 
  grid_id AS station_id,
  avg_temperature, 
  avg_humidity, 
  avg_wind_speed, 
  avg_sea_level_pressure, 
  avg_apparent_temperature, 
  avg_solar_radiation, 
  avg_pressure, 
  avg_dewpoint, 
  avg_snow, 
  avg_uv_index, 
  avg_precipitation, 
  avg_cloud_coverage, 
  CASE WHEN avg_temperature IS NOT NULL THEN 'grid' ELSE 'nearest_neighbor' END AS weather_calc
FROM "incidents-database"."incident_weather_left_join" WHERE avg_temperature IS NOT NULL
UNION
SELECT id_original, 
  latitude, 
  longitude, 
  emdcardnumber, 
  time_utc, 
  time_local, 
  response_time_sec, 
  day_of_week, 
  weekend_or_not, 
  geometry, 
  incident_id, 
  dist_to_seg, 
  xdsegid, 
  station_id,
  avg_temperature, 
  avg_humidity, 
  avg_wind_speed, 
  avg_sea_level_pressure, 
  avg_apparent_temperature, 
  avg_solar_radiation, 
  avg_pressure, 
  avg_dewpoint, 
  avg_snow, 
  avg_uv_index, 
  avg_precipitation, 
  avg_cloud_coverage, 
  'nearest_neighbor' AS weather_calc
FROM incidents_with_nearest_weather;